import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { TopBar } from "@/components/topbar";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { createAnnouncement, deleteAnnouncement, listAnnouncements } from "@/lib/platform.functions";
import { useTeacherGrades } from "@/lib/teacher-grades";
import { Trash2 } from "lucide-react";
export const Route = createFileRoute("/dashboard/announcements")({ component: Announcements });
function Announcements() { const qc = useQueryClient(); const { gradeNames } = useTeacherGrades(); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [grade, setGrade] = useState("all"); const [kind, setKind] = useState<"info" | "important">("info"); const { data: rows = [] } = useQuery({ queryKey: ["announcements"], queryFn: () => listAnnouncements() }); const publish = async () => { if (!title.trim()) return; await createAnnouncement({ data: { title: title.trim(), body, grade: grade === "all" ? null : grade, kind } }); setTitle(""); setBody(""); await qc.invalidateQueries({ queryKey: ["announcements"] }); }; return <><TopBar title="الإعلانات" /><main className="flex-1 space-y-6 p-6"><Card><CardHeader><CardTitle>إعلان جديد</CardTitle></CardHeader><CardContent className="space-y-3"><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="عنوان الإعلان" /><Textarea value={body} onChange={(e) => setBody(e.target.value)} placeholder="التفاصيل" /><div className="flex gap-2"><Select value={grade} onValueChange={setGrade}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">كل الصفوف</SelectItem>{gradeNames.map((g) => <SelectItem key={g} value={g}>{g}</SelectItem>)}</SelectContent></Select><Select value={kind} onValueChange={(v) => setKind(v as typeof kind)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="info">عادي</SelectItem><SelectItem value="important">مهم</SelectItem></SelectContent></Select><Button onClick={() => void publish()}>نشر</Button></div></CardContent></Card><Card><CardHeader><CardTitle>الإعلانات السابقة</CardTitle></CardHeader><CardContent className="space-y-2">{rows.length === 0 && <p className="text-sm text-muted-foreground">لا توجد إعلانات.</p>}{rows.map((a) => <div key={a.id} className="flex items-start gap-3 rounded-md border p-3"><div className="flex-1"><div className="font-medium">{a.title}</div><div className="text-sm text-muted-foreground">{a.body}</div><div className="mt-1 text-xs">{a.grade ?? "كل الصفوف"} · {new Date(a.createdAt).toLocaleString("ar-EG")}</div></div><Badge>{a.kind === "important" ? "مهم" : "عادي"}</Badge><Button size="icon" variant="ghost" onClick={() => void deleteAnnouncement({ data: { id: a.id } }).then(() => qc.invalidateQueries({ queryKey: ["announcements"] }))}><Trash2 className="h-4 w-4 text-destructive" /></Button></div>)}</CardContent></Card></main></>; }