import { createFileRoute, useParams } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { TopBar } from "@/components/topbar";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getStudentDetail } from "@/lib/platform.functions";
import { Loader2 } from "lucide-react";
export const Route = createFileRoute("/dashboard/students/$id")({ component: StudentProfile });
function StudentProfile() { const { id } = useParams({ from: "/dashboard/students/$id" }); const { data, isLoading } = useQuery({ queryKey: ["student", id], queryFn: () => getStudentDetail({ data: { studentId: id } }) }); if (isLoading || !data) return <><TopBar title="ملف الطالب" /><main className="flex flex-1 items-center justify-center"><Loader2 className="animate-spin" /></main></>; const s = data.student; return <><TopBar title={`ملف الطالب: ${s.name}`} /><main className="flex-1 space-y-6 p-6"><Card><CardContent className="space-y-2 pt-6"><h2 className="text-xl font-bold">{s.name}</h2><div dir="ltr">{s.email}</div><div>{s.phone || "لا يوجد هاتف"}</div><div dir="ltr">{s.studentCode || "لا يوجد رقم تعريفي"}</div><Badge variant="outline">{s.grade || "بدون صف"}</Badge></CardContent></Card><div className="grid gap-4 md:grid-cols-3"><Card><CardContent className="pt-6"><div className="text-2xl font-bold">{data.courses.length}</div><div className="text-sm text-muted-foreground">الدورات</div></CardContent></Card><Card><CardContent className="pt-6"><div className="text-2xl font-bold">{data.attempts.length}</div><div className="text-sm text-muted-foreground">محاولات الاختبارات</div></CardContent></Card><Card><CardContent className="pt-6"><div className="text-2xl font-bold">{data.avgScore === null ? "—" : `${data.avgScore}%`}</div><div className="text-sm text-muted-foreground">المتوسط</div></CardContent></Card></div><Card><CardHeader><CardTitle>الدورات المسجل بها</CardTitle></CardHeader><CardContent className="space-y-2">{data.courses.length === 0 && <p className="text-muted-foreground">لا توجد دورات.</p>}{data.courses.map((c) => <div key={c.id} className="rounded-md border p-3">{c.title} <span className="text-xs text-muted-foreground">· {new Date(c.at).toLocaleDateString("ar-EG")}</span></div>)}</CardContent></Card><Card><CardHeader><CardTitle>نتائج الاختبارات</CardTitle></CardHeader><CardContent className="p-0">{data.attempts.length === 0 ? <p className="p-6 text-muted-foreground">لا توجد نتائج.</p> : <Table><TableHeader><TableRow><TableHead className="text-right">الاختبار</TableHead><TableHead className="text-right">الدرجة</TableHead><TableHead className="text-right">التاريخ</TableHead></TableRow></TableHeader><TableBody>{data.attempts.map((a) => <TableRow key={a.id}><TableCell>{a.examTitle}</TableCell><TableCell><Badge variant={a.passed ? "default" : "destructive"}>{a.scorePct}%</Badge></TableCell><TableCell>{new Date(a.submittedAt).toLocaleString("ar-EG")}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card></main></>; }