import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { TopBar } from "@/components/topbar";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getStudentDetail } from "@/lib/platform.functions";
import { useAuth } from "@/lib/auth";
export const Route = createFileRoute("/student/stats")({ component: StudentStats });
function StudentStats() { const { user } = useAuth(); const { data } = useQuery({ queryKey: ["my-stats", user?.id], queryFn: () => getStudentDetail({ data: { studentId: user?.id ?? "" } }), enabled: !!user }); const attempts = data?.attempts ?? []; return <><TopBar title="الإحصائيات" /><main className="flex-1 space-y-6 p-6"><div className="grid gap-4 md:grid-cols-3"><Card><CardContent className="pt-6"><div className="text-2xl font-bold">{data?.avgScore === null || data?.avgScore === undefined ? "—" : `${data.avgScore}%`}</div><div className="text-muted-foreground">المعدل</div></CardContent></Card><Card><CardContent className="pt-6"><div className="text-2xl font-bold">{attempts.length}</div><div className="text-muted-foreground">المحاولات</div></CardContent></Card><Card><CardContent className="pt-6"><div className="text-2xl font-bold">{data?.courses.length ?? 0}</div><div className="text-muted-foreground">الدورات</div></CardContent></Card></div><Card><CardHeader><CardTitle>نتائجك</CardTitle></CardHeader><CardContent className="p-0">{attempts.length === 0 ? <p className="p-8 text-center text-muted-foreground">لا توجد نتائج بعد.</p> : <Table><TableHeader><TableRow><TableHead className="text-right">الاختبار</TableHead><TableHead className="text-right">الدرجة</TableHead><TableHead className="text-right">الحالة</TableHead></TableRow></TableHeader><TableBody>{attempts.map((a) => <TableRow key={a.id}><TableCell>{a.examTitle}</TableCell><TableCell>{a.scorePct}%</TableCell><TableCell><Badge variant={a.passed ? "default" : "destructive"}>{a.passed ? "ناجح" : "راسب"}</Badge></TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card></main></>; }