/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ExamsExamIdRouteImport } from './routes/exams.$examId'
import { Route as DashboardTeachersRouteImport } from './routes/dashboard.teachers'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as GradesGradeIndexRouteImport } from './routes/grades.$grade.index'
import { Route as DashboardCoursesIndexRouteImport } from './routes/dashboard.courses.index'
import { Route as DashboardCoursesIdRouteImport } from './routes/dashboard.courses.$id'
import { Route as GradesGradeTeachersTeacherIdRouteImport } from './routes/grades.$grade.teachers.$teacherId'

const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ExamsExamIdRoute = ExamsExamIdRouteImport.update({
  id: '/exams/$examId',
  path: '/exams/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeachersRoute = DashboardTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => DashboardRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesGradeIndexRoute = GradesGradeIndexRouteImport.update({
  id: '/grades/$grade/',
  path: '/grades/$grade/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCoursesIndexRoute = DashboardCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesIdRoute = DashboardCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const GradesGradeTeachersTeacherIdRoute =
  GradesGradeTeachersTeacherIdRouteImport.update({
    id: '/grades/$grade/teachers/$teacherId',
    path: '/grades/$grade/teachers/$teacherId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/dashboard/teachers': typeof DashboardTeachersRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/courses/$id': typeof DashboardCoursesIdRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/grades/$grade/': typeof GradesGradeIndexRoute
  '/grades/$grade/teachers/$teacherId': typeof GradesGradeTeachersTeacherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/dashboard/teachers': typeof DashboardTeachersRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/courses/$id': typeof DashboardCoursesIdRoute
  '/dashboard/courses': typeof DashboardCoursesIndexRoute
  '/grades/$grade': typeof GradesGradeIndexRoute
  '/grades/$grade/teachers/$teacherId': typeof GradesGradeTeachersTeacherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/dashboard/teachers': typeof DashboardTeachersRoute
  '/exams/$examId': typeof ExamsExamIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/courses/$id': typeof DashboardCoursesIdRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/grades/$grade/': typeof GradesGradeIndexRoute
  '/grades/$grade/teachers/$teacherId': typeof GradesGradeTeachersTeacherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/me'
    | '/courses/$courseId'
    | '/dashboard/teachers'
    | '/exams/$examId'
    | '/dashboard/'
    | '/dashboard/courses/$id'
    | '/dashboard/courses/'
    | '/grades/$grade/'
    | '/grades/$grade/teachers/$teacherId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/me'
    | '/courses/$courseId'
    | '/dashboard/teachers'
    | '/exams/$examId'
    | '/dashboard'
    | '/dashboard/courses/$id'
    | '/dashboard/courses'
    | '/grades/$grade'
    | '/grades/$grade/teachers/$teacherId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/me'
    | '/courses/$courseId'
    | '/dashboard/teachers'
    | '/exams/$examId'
    | '/dashboard/'
    | '/dashboard/courses/$id'
    | '/dashboard/courses/'
    | '/grades/$grade/'
    | '/grades/$grade/teachers/$teacherId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  ExamsExamIdRoute: typeof ExamsExamIdRoute
  GradesGradeIndexRoute: typeof GradesGradeIndexRoute
  GradesGradeTeachersTeacherIdRoute: typeof GradesGradeTeachersTeacherIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/exams/$examId': {
      id: '/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof ExamsExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teachers': {
      id: '/dashboard/teachers'
      path: '/teachers'
      fullPath: '/dashboard/teachers'
      preLoaderRoute: typeof DashboardTeachersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades/$grade/': {
      id: '/grades/$grade/'
      path: '/grades/$grade'
      fullPath: '/grades/$grade/'
      preLoaderRoute: typeof GradesGradeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/courses/': {
      id: '/dashboard/courses/'
      path: '/courses'
      fullPath: '/dashboard/courses/'
      preLoaderRoute: typeof DashboardCoursesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses/$id': {
      id: '/dashboard/courses/$id'
      path: '/courses/$id'
      fullPath: '/dashboard/courses/$id'
      preLoaderRoute: typeof DashboardCoursesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/grades/$grade/teachers/$teacherId': {
      id: '/grades/$grade/teachers/$teacherId'
      path: '/grades/$grade/teachers/$teacherId'
      fullPath: '/grades/$grade/teachers/$teacherId'
      preLoaderRoute: typeof GradesGradeTeachersTeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardTeachersRoute: typeof DashboardTeachersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCoursesIdRoute: typeof DashboardCoursesIdRoute
  DashboardCoursesIndexRoute: typeof DashboardCoursesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardTeachersRoute: DashboardTeachersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCoursesIdRoute: DashboardCoursesIdRoute,
  DashboardCoursesIndexRoute: DashboardCoursesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  ExamsExamIdRoute: ExamsExamIdRoute,
  GradesGradeIndexRoute: GradesGradeIndexRoute,
  GradesGradeTeachersTeacherIdRoute: GradesGradeTeachersTeacherIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
