/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GradesGradeRouteImport } from './routes/grades.$grade'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as GradesGradeTeachersTeacherIdRouteImport } from './routes/grades.$grade.teachers.$teacherId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesGradeRoute = GradesGradeRouteImport.update({
  id: '/grades/$grade',
  path: '/grades/$grade',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesGradeTeachersTeacherIdRoute =
  GradesGradeTeachersTeacherIdRouteImport.update({
    id: '/teachers/$teacherId',
    path: '/teachers/$teacherId',
    getParentRoute: () => GradesGradeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/grades/$grade': typeof GradesGradeRouteWithChildren
  '/grades/$grade/teachers/$teacherId': typeof GradesGradeTeachersTeacherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/grades/$grade': typeof GradesGradeRouteWithChildren
  '/grades/$grade/teachers/$teacherId': typeof GradesGradeTeachersTeacherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/grades/$grade': typeof GradesGradeRouteWithChildren
  '/grades/$grade/teachers/$teacherId': typeof GradesGradeTeachersTeacherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/courses/$courseId'
    | '/grades/$grade'
    | '/grades/$grade/teachers/$teacherId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/courses/$courseId'
    | '/grades/$grade'
    | '/grades/$grade/teachers/$teacherId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/courses/$courseId'
    | '/grades/$grade'
    | '/grades/$grade/teachers/$teacherId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  GradesGradeRoute: typeof GradesGradeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades/$grade': {
      id: '/grades/$grade'
      path: '/grades/$grade'
      fullPath: '/grades/$grade'
      preLoaderRoute: typeof GradesGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades/$grade/teachers/$teacherId': {
      id: '/grades/$grade/teachers/$teacherId'
      path: '/teachers/$teacherId'
      fullPath: '/grades/$grade/teachers/$teacherId'
      preLoaderRoute: typeof GradesGradeTeachersTeacherIdRouteImport
      parentRoute: typeof GradesGradeRoute
    }
  }
}

interface GradesGradeRouteChildren {
  GradesGradeTeachersTeacherIdRoute: typeof GradesGradeTeachersTeacherIdRoute
}

const GradesGradeRouteChildren: GradesGradeRouteChildren = {
  GradesGradeTeachersTeacherIdRoute: GradesGradeTeachersTeacherIdRoute,
}

const GradesGradeRouteWithChildren = GradesGradeRoute._addFileChildren(
  GradesGradeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  GradesGradeRoute: GradesGradeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
